module.exports = [
    'id',
    'name',
    'description',
    'author',
    'owner',
    'created',
    'modified',
    'modified_by',
    'deleted',
    'hidden',
    'statistics',
    'index_version',
    'generation_num',
    'client_state',
    'schema_stripe',
    'db_stripe',
    'resolvedObjects'
];
